config/routes.rb
Rails.application.routes.draw do
  resources :orders
  match '/recieving', to: 'orders#recieving', via: 'get', as: 'recieving'
  match '/remove_item', to: 'orders#remove_item', via: 'post', as: 'remove_item'
  match '/update_values', to: 'orders#update_values', via: 'post', as: 'update_values'
  match '/orders/print/:id', to: 'orders#print', via: 'get', as: 'print_order'

  resources :inventories

  resources :parts
  match '/catalog', to: 'parts#catalog', via: 'get', as: 'catalog'

  match '/add_part', to: 'carts#add_part', via: 'post', as: 'add_part'
  match '/remove_part', to: 'carts#remove_part', via: 'post', as: 'remove_part'
  match '/update_part', to: 'carts#update_part', via: 'post', as: 'update_part'
  match '/update_part_keep', to: 'carts#update_part_keep', via: 'post', as: 'update_part_keep'
  match '/item_count', to: 'carts#item_count', via: 'post', as: 'item_count'

  devise_for :users
  resources :users
  match '/users/add_user',    to: 'users#add_user',    via: 'post', as: 'add_user'
  match '/users/remove_user', to: 'users#remove_user', via: 'post', as: 'remove_user'
  match '/users/update_role', to: 'users#update_role', via: 'post', as: 'update_role'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/admin', to: 'admin#index', via: 'get', as: 'admin'

  match '/pos', to: 'pos#index', via: 'get', as: 'pos'
  match '/pos/returns', to: 'pos#returns', via: 'get', as: 'returns'
  match '/pos/recipt/:id', to: 'pos#recipt', via: 'get', as: 'recipt'

  resources :transactions, :only => [:show, :index, :destroy]
  match '/transactions/get_totals', to: 'transactions#get_totals', via: 'post', as: 'get_totals'
  match '/transactions/get_cart', to: 'transactions#get_cart', via: 'post', as: 'get_cart'
  match '/checkout', to: 'transactions#checkout', via: 'post', as: 'checkout'
  match '/return', to: 'transactions#return', via: 'post', as: 'return'

  match '/reports/daily', to: 'reports#daily', via: 'get', as: 'daily_report'
  match '/reports/weekly', to: 'reports#weekly', via: 'get', as: 'weekly_report'
  match '/reports/monthly', to: 'reports#monthly', via: 'get', as: 'monthly_report'
  match '/reports/quarterly', to: 'reports#quarterly', via: 'get', as: 'quarterly_report'
  match '/reports/yearly', to: 'reports#yearly', via: 'get', as: 'yearly_report'
  match '/reports/audit', to: 'reports#audit', via: 'get', as: 'audit_report'
  match '/reports/po', to: 'reports#po_report', via: 'get', as: 'po_report'
  match '/reports/inventory', to: 'reports#inventory', via: 'get', as: 'inventory_report'

end

app/views/admin/index.html.erb
<div class="screen">
	<div class ="row">
		<div class="col-sm-4">
			<h2 class="title">Sales Reports</h2>
		</div>
	</div>
	<div class ="row">
		<div class="col-sm-4">
			<table class="finish centered">
					<tr>
						<td><button class = "btn1" onclick="goto('<%= daily_report_path(format: :pdf) %>')">Day</button></td>
						<td><button class = "btn1" onclick="goto('<%= weekly_report_path(format: :pdf) %>')">Week</button></td>
					</tr>	
					<tr>
						<td><button class = "btn1">Month</button></td>
						<td><button class = "btn1">Quarter</button></td>
					</tr>	
					<tr>
						<td><button class = "btn1">Year</button></td>
						<td><button class = "btn1">Audit</button></td>
					</tr>	
					<tr>
						<td><button class = "btn1">PO</button></td>
						<td><button class = "btn1" onclick="goto('<%= inventory_report_path(format: :pdf) %>')">Inventory</button></td>
					</tr>	
				</table>
		</div>
		<div class="col-sm-2">
			<table class="finish centered">
				<tr>
					<td><button class = "btn1" onclick="goto('<%= parts_path%>')">Inventory</button></td>
				</tr>	
				<tr>
					<td><button class = "btn1" onclick="goto('<%= orders_path%>')">Orders</button></td>
				</tr>
				<tr>
					<td><button class = "btn1" onclick="goto('<%= users_path%>')">Users</button></td>
				</tr>
				<tr>
					<td><button class = "btn1" onclick="goto('<%= pos_path%>')">POS</button></td>
				</tr>
			</table>
		</div>
		<div class="col-sm-5">
			<div class="inventory_partial">
				<%=render "inventories/inventory"%>
			</div>
		</div>	
	</div>

	<div class="modal fade" id="dayModal" tabindex="-1" role="dialog" aria-labelledby="dayModal" aria-hidden="true">
			<div class="modal-dialog">
		    <div class="modal-content">
		        <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
		        <h4 class="modal-title" id="myModalLabel">What Day?</h4>
		        </div>
		        <div class="modal-body">
		            <form>
		            	Quantity:<br>
					<input type="text" name="quantity" id = "quantity">
					<input type="hidden" name="part_id" id="part_id">
					<br>
		            </form>

		        </div>
		        <div class="modal-footer">
		            <button type="button" class="btn btn-default" data-dismiss="modal">Done</button>
			    </div>
		    </div>
		  </div>
		</div>
</div>