config/routes.rb
Rails.application.routes.draw do
  resources :orders
  match '/recieving', to: 'orders#recieving', via: 'get', as: 'recieving'
  match '/remove_item', to: 'orders#remove_item', via: 'post', as: 'remove_item'
  match '/update_values', to: 'orders#update_values', via: 'post', as: 'update_values'
  match '/orders/print/:id', to: 'orders#print', via: 'get', as: 'print_order'

  resources :inventories

  resources :parts
  match '/catalog', to: 'parts#catalog', via: 'get', as: 'catalog'

  match '/add_part', to: 'carts#add_part', via: 'post', as: 'add_part'
  match '/remove_part', to: 'carts#remove_part', via: 'post', as: 'remove_part'
  match '/update_part', to: 'carts#update_part', via: 'post', as: 'update_part'
  match '/update_part_keep', to: 'carts#update_part_keep', via: 'post', as: 'update_part_keep'
  match '/item_count', to: 'carts#item_count', via: 'post', as: 'item_count'

  devise_for :users
  resources :users
  match '/users/add_user',    to: 'users#add_user',    via: 'post', as: 'add_user'
  match '/users/remove_user', to: 'users#remove_user', via: 'post', as: 'remove_user'
  match '/users/update_role', to: 'users#update_role', via: 'post', as: 'update_role'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/admin', to: 'admin#index', via: 'get', as: 'admin'

  match '/pos', to: 'pos#index', via: 'get', as: 'pos'
  match '/pos/returns', to: 'pos#returns', via: 'get', as: 'returns'
  match '/pos/recipt/:id', to: 'pos#recipt', via: 'get', as: 'recipt'

  resources :transactions, :only => [:show, :index, :destroy]
  match '/transactions/get_totals', to: 'transactions#get_totals', via: 'post', as: 'get_totals'
  match '/transactions/get_cart', to: 'transactions#get_cart', via: 'post', as: 'get_cart'
  match '/checkout', to: 'transactions#checkout', via: 'post', as: 'checkout'
  match '/return', to: 'transactions#return', via: 'post', as: 'return'

  match '/reports/daily', to: 'reports#daily', via: 'get', as: 'daily_report'
  match '/reports/weekly', to: 'reports#weekly', via: 'get', as: 'weekly_report'
  match '/reports/monthly', to: 'reports#monthly', via: 'get', as: 'monthly_report'
  match '/reports/quarterly', to: 'reports#quarterly', via: 'get', as: 'quarterly_report'
  match '/reports/yearly', to: 'reports#yearly', via: 'get', as: 'yearly_report'
  match '/reports/audit', to: 'reports#audit', via: 'get', as: 'audit_report'
  match '/reports/po', to: 'reports#po_report', via: 'get', as: 'po_report'
  match '/reports/inventory', to: 'reports#inventory', via: 'get', as: 'inventory_report'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :cas_authenticatable
  
  extend FriendlyId
  friendly_id :username, use: :slugged
  
  belongs_to :role
  belongs_to :cart, autosave: true
  has_many :transactions

  before_create :set_default_role
  before_save :set_default_email
  # before_create :set_default_confrim

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  YEAR_REGEX = /\A[1-4][A-B]\Z/
  PHONE_REGEX = /\A[0-9]{10}|([0-9]{3})-[0-9]{3}-[0-9]{4}|\Z/

  validates :username, presence: true 
  validates :term,  allow_nil: true,
                    length: { maximum: 2 }, 
                    format: { with: YEAR_REGEX }
  validates :email, allow_nil: true, format:     { with: VALID_EMAIL_REGEX }
  validates :phonenumber, allow_nil: true,
                          length: { maximum: 10 },
                          format: { with: PHONE_REGEX }

  def student?
    self.role == Role.find_by_name('Student')
  end

  def admin?
    self.role == Role.find_by_name('Admin')
  end

  def ordering_officer?
    self.role == Role.find_by_name('Ordering Officer')
  end

  def staff?
    self.role == Role.find_by_name('Staff')
  end

  def vpfin?
    self.role == Role.find_by_name('VPFin')
  end

  def manager?
    self.role == Role.find_by_name('Manager')
  end

  def confirmed?
    self.confirm
  end

  def tier_one?
    tier_two? || staff? || manager?
  end

  def tier_two?
    tier_three? || ordering_officer?
  end

  def tier_three?
    admin? || vpfin?
  end

  def full_name
    "#{firstname} #{lastname}"
  end

  private

    def set_default_role 
    	self.role ||= Role.find_by_name('Student') 
    end

    def set_default_confrim
      self.confirm ||= false
    end

    def set_default_email
      self.email ||= "#{self.username}@uwaterloo.ca"
    end
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update, :show]
	before_action :tier_three,   only: [:index, :update_role, :remove_user]

	def index 
		@users = User.all
		@user = User.new
	end

	def show
		@user = User.friendly.find(params[:id])
	end

	def edit
		@user = current_user
	end

	def update
		if @user.update_attributes(user_params)
			@user.update_attribute(:confirm, true)
			flash[:success] = "Profile updated"
			redirect_to current_user 
		else
			render 'edit'
		end
	end

	def update_role
		respond_to do |format|
			role = Role.find(params[:user][:role_id])
			user = User.friendly.find(params[:user][:username])
			if user !=  current_user
				if !current_user.admin? && ( !(user.role.name.eql? "Admin") && !(user.role.name.eql? "VPFin") ) || current_user.admin?
					if user.update_attribute(:role, role)	
						format.html { redirect_to :back, flash: {success: "#{user.username} role has been updated"} }
						current_user.save
					else
						format.html { redirect_to :back, flash: {danger: "An error occured"} }
					end
				else
					format.html { redirect_to :back, flash: {danger: "You do not have the ability to complete this action"} }
				end
			else
				format.html { redirect_to :back, flash: {danger: "You can't change your own role"} }
			end
		end
	end

	def remove_user
		respond_to do |format|
			if user = User.friendly.find(params[:user][:username])
				if user != current_user
					puts user.role.name
					puts !(user.role.name.eql? "Admin")
					puts !(user.role.name.eql? "VPFin")
					if !current_user.admin? && ( !(user.role.name.eql? "Admin") && !(user.role.name.eql? "VPFin") ) || current_user.admin?
						if user.destroy
							format.html { redirect_to :back, flash: {success:"#{params[:user][:username]} has been removed" } }
						else
							format.html { redirect_to :back, flash: {danger: "An error occured"} }
						end
					else
						format.html { redirect_to :back, flash: {danger: "You do not have the ability to complete this action"} }
					end
				else 
					format.html { redirect_to :back, flash: {danger: "You can't delete yourself"} }
				end
			else 
				format.html { redirect_to :back, flash: {danger: "#{params[:user][:username]} could not be found"}}	
			end
		end
	end

	def add_user
		respond_to do |format|
			if @user = User.new(user_params)
				if !current_user.admin? && ( !(@user.role.name.eql? "Admin") && !(@user.role.name.eql? "VPFin") ) || current_user.admin?
					if @user.save 
						format.html { redirect_to :back, flash: {success: "#{@user.username} has been added as a #{@user.role.name}"} }
						format.json { render json: @user }
					else
						format.html { redirect_to :back, {danger:  "#{@user.errors.count}" } }
					end
				else
					format.html { redirect_to :back, flash: {danger: "You do not have the ability to complete this action"} }
				end 
			else
			 format.html { redirect_to :back, {danger: "An error occured" } }
			end
		end
	end

	private 

		def user_params
			params.require(:user).permit(:username, :role_id, :firstname, :lastname, :email, :phonenumber, :program, :term, :year)
		end

		def correct_user
			@user = User.friendly.find(params[:id])
			redirect_to(root_url) unless current_user == @user
		end

		def admin_user 
			redirect_to(root_url) unless current_user.admin?
		end
end

app/views/users/_editProfile.html.erb
<% provide(:title, "Edit User") %>
<!--h1>Update your Profile</h1-->

<div class="row">
	<div class="col-md-6">
		<%= form_for @user do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
				<div>
					<%= f.label :firstname, "First Name"%>
					<%= f.text_field :firstname, :value => @user.firstname %><br>
					<%= f.label :lastname, "Last Name", :class => "" %>
					<%= f.text_field :lastname, :value => @user.lastname %><br>
					<%= f.label :email, :class => "" %>
					<%= f.text_field :email, :value => @user.email %><br>
					<%= f.label :phonenumber, "Phone Number"%>
					<%= f.text_field :phonenumber, :value => @user.phonenumber %><br>
					<%= f.label :program, :class => "" %>
					<%= f.collection_select(:program, Program.all, :id, :name) %><br>
					<%= f.label :term, :class => "" %>
					<%= f.select(:term, options_for_select(["1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B"], @user.term)) %><br>
					<%= f.label :year, "Year of Graduation",  :class => "" %>
					<%= f.select(:year, options_for_select(((Time.now.year - 20)..(Time.now.year + 20)).to_a, @user.year)) %><br>
					

					<div style="padding: 10px;">
						<div>
							<table>
								<tr>
									<td><%= f.submit "Save", :class => "btn1"%></td>
									<!--td><%= link_to 'Back', @user, :class => "btn1"%></td-->
								</tr>
							</table>
						</div>
					</div>
				</div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Update your Profile</h1>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
					<div class="form-group">
						<%= f.label :firstname, "First Name", :class => "control-label" %>
						<div class="controls">
							<%= f.text_field :firstname, :value => @user.firstname %>
						</div>

						<%= f.label :lastname, "Last Name", :class => "control-label" %>
						<div class="controls">
							<%= f.text_field :lastname, :value => @user.firstname %>
						</div>

						<%= f.label :email, :class => "control-label" %>
						<div class="controls">
							<%= f.text_field :email, :value => @user.email %>
						</div>

						<%= f.label :phonenumber, "Phone Number", :class => "control-label" %>
						<div class="controls">
							<%= f.text_field :phonenumber, :value => @user.phonenumber %>
						</div>

						<%= f.label :program, :class => "control-label" %>
						<div class="controls">
							<%= f.collection_select(:program, Program.all, :id, :name) %>
						</div>

						<%= f.label :term, :class => "control-label" %>
						<div class="controls">
							<%= f.select(:term, options_for_select(["1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B"], @user.term)) %>
						</div>
						
						<%= f.label :year, :class => "control-label" %>
						<div class="controls">
							<%= f.select(:year, options_for_select(((Time.now.year - 20)..(Time.now.year + 20)).to_a, @user.year)) %>
						</div>

						<div class="control-group" style="padding: 10px;">
							<div class="controls">
								<%= f.submit "Save Changes", :class => "" %>
								<%= link_to 'Back', @user, :class => "" %>
							</div>
						</div>
					</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-sm-1">
	</div>
	<div class="col-sm-6"> 
		<div class ="catalog_partial">
			<div class="table-responsive"> 
				<table class="table">
					<tr>
						<th>First Name</th>
						<th>Last Name</th>
						<th>WatIAM ID</th>
						<th>Role</th>
						<th>Email</th>
					</tr>
					<% @users.each do |user| %>
						<tr class="user_row clickable-row onhover" id="user_<%= user.username %>" data="<%= user.username %>" onclick="inputusername('<%= user.username %>');">
							<td><%= user.firstname %></td>
							<td><%= user.lastname %></td>
							<td><%= user.username %></td>
							<td><%= user.role.name %></td>
							<td><%= user.email %></td>
						</tr>		
					<% end %>
				</table>
			</div>
		</div>
	</div>
	<div class="col-sm-4">
		

		<div class="panel">
			<div id="add-user-panel" class="container">
				<h3>Add Users</h3>
				<%= form_for @user, :url => add_user_path do |f| %>
					<% if flash[:user_notice] %>
						<div class="notice"><%= flash[:user_notice] %></div>
					<% end %>

					<%= f.label :username, :class => "control-label" %>
					<div class="controls">
						<%= f.text_field :username %>
					</div>

					<%= f.label :role, :class => "control-label" %>
					<div class="controls">
						<%= f.collection_select(:role_id, Role.all, :id, :name) %>
					</div>

					<div class="control-group" style="padding: 10px;">
						<div class="controls">
							<%= f.submit "Add User", :class => "" %>
						</div>
					</div>
				<% end %>
			</div>
		
			<div id="remove-user-panel" class="container">
			<h3>Remove Users</h3>
				<%= form_for @user, :url => remove_user_path, html: {:onsubmit => "return confirm('Do you really want to delete this user?');"}  do |f| %>
					<%= f.label :username, :class => "control-label" %>
					<div class="controls">
						<%= f.text_field :username, :class => "username-input", :enabled => false %>
					</div>

					<div class="control-group" style="padding: 10px;">
						<div class="controls">
							<%= f.submit "Remove User", :class => "" %>
						</div>
					</div>
				<% end %>
			</div>

			<div id="change-roles-panel" class="container">
			<h3>Change Roles</h3>
				<%= form_for @user, :url => update_role_path, :onsubmit => "return confirm('Are you sure you want to change the user roles?');" do |f| %>
					<%= f.label :username, :class => "control-label" %>
					<div class="controls">
						<%= f.text_field :username, :class => "username-input", :enabled => false %>
					</div>

					<%= f.label :role, :class => "control-label" %>
					<div class="controls">
						<%= f.collection_select(:role_id, Role.all, :id, :name) %>
					</div>

					<div class="control-group" style="padding: 10px;">
						<div class="controls">
							<%= f.submit "Update Roles", :class => "" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>

		<table class="finish centre">
			<tr>
				<td><button class = "btn1" id="user" onclick="showadd()">Add</button></td>
				<td><button class = "btn1" id="user" onclick="showremove()">Remove</button></td>
				<td><button class = "btn1" id="user" onclick="showroles()">Update</button></td>
			</tr>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1><%= @user.username %></h1>
			<h2><b>Position: </b><%= @user.role.name %></h2>
			<p><b>First Name:</b> <%= @user.firstname %></p>
			<p><b>Last Name:</b> <%= @user.lastname %></p>
			<p><b>Email:</b> <%= @user.email %></p>
			<p><b>Phone Number:</b> <%= @user.phonenumber %></p>
			<p><b>Program:</b> <%= Program.find(@user.program).name unless @user.program == nil %></p>
			<p><b>Year of Graduation:</b> <%= @user.year %></p>
			<p><%= link_to 'Edit', edit_user_path, class: "" %></p>
			<h3>Functions</h3>
			<table>
				<% if @user.admin? || @user.vpfin?%>
					<td><button class = "btn2" onclick="goto('<%= admin_path%>')">Admin</button></td>
				<% elsif @user.ordering_officer? %>
					<td><button class = "btn1" onclick="goto('<%= pos_path%>')">POS</button></td>
					<td><button class = "btn1" onclick="goto('<%= orders_path%>')">POS</button></td>
				<% elsif @user.staff? %>
					<td><button class = "btn2" onclick="goto('<%= pos_path%>')">POS</button></td>
				<% end %>
			</table>
		</div>
	</div>
</div>