config/routes.rb
Rails.application.routes.draw do
  resources :orders
  match '/recieving', to: 'orders#recieving', via: 'get', as: 'recieving'
  match '/remove_item', to: 'orders#remove_item', via: 'post', as: 'remove_item'
  match '/update_values', to: 'orders#update_values', via: 'post', as: 'update_values'
  match '/orders/print/:id', to: 'orders#print', via: 'get', as: 'print_order'

  resources :inventories

  resources :parts
  match '/catalog', to: 'parts#catalog', via: 'get', as: 'catalog'

  match '/add_part', to: 'carts#add_part', via: 'post', as: 'add_part'
  match '/remove_part', to: 'carts#remove_part', via: 'post', as: 'remove_part'
  match '/update_part', to: 'carts#update_part', via: 'post', as: 'update_part'
  match '/update_part_keep', to: 'carts#update_part_keep', via: 'post', as: 'update_part_keep'
  match '/item_count', to: 'carts#item_count', via: 'post', as: 'item_count'

  devise_for :users
  resources :users
  match '/users/add_user',    to: 'users#add_user',    via: 'post', as: 'add_user'
  match '/users/remove_user', to: 'users#remove_user', via: 'post', as: 'remove_user'
  match '/users/update_role', to: 'users#update_role', via: 'post', as: 'update_role'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/admin', to: 'admin#index', via: 'get', as: 'admin'

  match '/pos', to: 'pos#index', via: 'get', as: 'pos'
  match '/pos/returns', to: 'pos#returns', via: 'get', as: 'returns'
  match '/pos/recipt/:id', to: 'pos#recipt', via: 'get', as: 'recipt'

  resources :transactions, :only => [:show, :index, :destroy]
  match '/transactions/get_totals', to: 'transactions#get_totals', via: 'post', as: 'get_totals'
  match '/transactions/get_cart', to: 'transactions#get_cart', via: 'post', as: 'get_cart'
  match '/checkout', to: 'transactions#checkout', via: 'post', as: 'checkout'
  match '/return', to: 'transactions#return', via: 'post', as: 'return'

  match '/reports/daily', to: 'reports#daily', via: 'get', as: 'daily_report'
  match '/reports/weekly', to: 'reports#weekly', via: 'get', as: 'weekly_report'
  match '/reports/monthly', to: 'reports#monthly', via: 'get', as: 'monthly_report'
  match '/reports/quarterly', to: 'reports#quarterly', via: 'get', as: 'quarterly_report'
  match '/reports/yearly', to: 'reports#yearly', via: 'get', as: 'yearly_report'
  match '/reports/audit', to: 'reports#audit', via: 'get', as: 'audit_report'
  match '/reports/po', to: 'reports#po_report', via: 'get', as: 'po_report'
  match '/reports/inventory', to: 'reports#inventory', via: 'get', as: 'inventory_report'

end

app/controllers/pos_controller.rb
class PosController < ApplicationController
	helper_method :sort_column, :sort_direction
	before_filter :tier_one, only: [:index, :returns, :recipt]


	def index
		if !current_user.cart 
			current_user.cart = Cart.new
			current_user.cart.owner = current_user.username
			current_user.cart.save!
		end
		@cart = current_user.cart
		@parts_in_cart = @cart.parts_in_cart
		@parts = Part.joins(:inventory).onSale.order(sort_column + " " + sort_direction)
	end

	def returns
		trans_id = params[:transaction_id]
		@transaction = trans_id != nil ? Transaction.find(trans_id) : nil
		@cart_to_return = @transaction != nil ? Cart.find(@transaction.cart_id) : nil
		@parts_in_cart = @cart_to_return != nil ? @cart_to_return.parts_in_cart : nil
		
		# Getting the returning cart from the session 
		@cart_retruning = nil
		if session[:returns_cart]
			@cart_retruning = Cart.find_by(id: session[:returns_cart])
			puts @cart_retruning
			if !@cart_retruning
				@cart_retruning = Cart.new
				@cart_retruning.owner = "#{current_user.username}_returns"
				@cart_retruning.save!
				session[:returns_cart] = @cart_retruning.id
			else 
				@cart_retruning = Cart.find(session[:returns_cart])
			end
		else
			@cart_retruning = Cart.find_by({owner: "#{current_user.username}_returns"})
			if !@cart_retruning 
				@cart_retruning = Cart.new
				@cart_retruning.owner = "#{current_user.username}_returns"
				@cart_retruning.save!
				session[:returns_cart] = @cart_retruning.id	
			end
		end
		@parts_returning_cart = @cart_retruning.parts_in_cart
		# Delete all entries in this cart on refresh
		@parts_returning_cart.each do |part|
		part.destroy!
	end

		if @parts_in_cart && @parts_returning_cart.length != @parts_in_cart.length
=begin
			@parts_returning_cart.each do |part|
				part.destroy!
			end
=end			
			# Fill the cart with stuff
			@parts_in_cart.each do |part|
				pic = PartsInCart.new({part_id:part.part_id, cart_id:@cart_retruning.id})
				pic.quantity_requested = 0
				@parts_returning_cart << pic
			end
			@cart_retruning.save!
		end
 	end

 	def recipt
 		@transaction = Transaction.find(params[:id])
 		@cart = Cart.find(@transaction.cart_id)
 		@parts_in_cart = @cart.parts_in_cart
 		respond_to do |format|
	  		if @transaction
	    		format.pdf do
	      	 	render pdf: "RigidWare - Recipt #{@transaction.id} - #{Time.zone.now.to_date}",
	             		   template: 'pos/recipt.pdf.html',
	             		   disposition: 'attachment'
	      		end
	    	end
	    end
 	end

 	private
 		def sort_column 
 			%w[part_number description price].include?(params[:sort]) ? params[:sort] : "part_number"
 		end

 		def sort_direction
 			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc" 
 		end

 		def permision
			redirect_to(root_url) unless current_user.admin? || current_user.manager? || current_user.vpfin?
		end

		def admin
			redirect_to(root_url) unless current_user.admin?
		end

		def manager 
			redirect_to(root_url) unless current_user.manager?
		end
end

app/helpers/pos_helper.rb
module PosHelper
end

app/views/pos/index.html.erb
<!--This is the HTML for the POS system-->
<div>
	<div class="screen">
		<div class "row">
			<!--this is the left 1/2 of the screen-->
			<div class="col-sm-6" >
				<h1>Cart</h1>
				<div class="cart_partial">
					<%= hidden_field_tag :cart_id, @cart.id %>
					<%=render "carts/cart"%>
				</div>
				<!--display the left side of the options below cart-->
				<div class="complete transaction">
					<table class="finish fit" cellspacing="10">
						<tr class="finish">
							<!--change back to text later-->
							<td><button class = "btn2" id="total" onclick = "get_total(<%= @cart.id %>)">Total</button></td>
							<td class="label1" id="show_total"><div class="sizing">0.00</div></td>
						</tr>
						<tr class="finish">
							<td><button  class = "btn2" onclick ="calc_change()">Tendered</button></td>
							<td><input type="text" id="tendered" value="0.00"></td>
						</tr>
						<tr class="finish">
							<td class="label1">Change due</td>
							<td class="label1"  id="change">0.00</td>
						</tr>
						<tr class="finish">
							<td class="label1">Student ID</td>
							<td><input type="text" id="watiam" value=""></td>
						</tr>
						<tr class="finish">
							<!--td><button class = "btn2">Print Reciept</button></td-->
							<td><button class = "btn2" onclick="checkout(<%= @cart.id %>)">Checkout</button></td>
						</tr>
					</table>
				</div>
			</div>
			<!--this is the right 1/2 of the screen-->
			<div class="col-sm-6">
				<h1>Inventory</h1>
				<div class ="catalog_partial">
					<%=render "shared/catalog"%>
				</div>
				<br>
				<div class ="POS_admin_buttons">

					<table class="centre fit">
						<tr>
							<td><button class = "btn1" onclick="goto('<%= orders_path %>')">Place Order</button></td>
							<td><button class = "btn1" onclick="goto('<%= returns_path %>')">Return</button></td>
							<td><button class = "btn1" onclick="goto('<%= transactions_path %>')">Transac.</button></td>
							<td><button class = "btn1" onclick="goto('<%= daily_report_path(format: :pdf) %>')">Today's Sales</button></td>
						</tr>
					</table>
				</div>
			</div>
		</div>

		<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
			<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
				<h4 class="modal-title" id="myModalLabel">Update Count</h4>
				</div>
				<div class="modal-body">
					<form>
						Quantity:<br>
					<input type="text" name="quantity" id = "quantity">
					<input type="hidden" name="part_id" id="part_id">
					<br>
					</form>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal" onclick="add_quantity_manually(<%=@cart.id%>, quantity, part_id)">Done</button>
				</div>
			</div>
		  </div>
		</div>
	</div>
</div>

app/views/pos/returns.html.erb
<form>
	<b>Trasaction ID:</b>
	<input type="text" name="transaction_id" id="transaction_id" value="<%= @transaction.id unless @transaction == nil %>">
	<a class="" onclick="get_trans_cart()">Submit</a>
</form>
<br>
<div class "row">
	<!--this is the left 1/2 of the screen-->
	<div class="col-sm-6">
		<div id="transaction" class ="cart_partial  cart">
			<% if @transaction %>
				<%=render "carts/return_cart", f: @parts_in_cart, add: false %>
			<% end %>
		</div>

	</div>	
	<!--this is the right 1/2 of the screen-->
	<div class="col-sm-6">
		<div id="returns" class ="cart_partial cart">
			<input type="hidden" name="returning_id" id="returning_id" value="<%= @cart_retruning.id unless @cart_retruning == nil %>">
			<%=render "carts/return_cart", f: @parts_returning_cart, add: true %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-offset-7">
		<div>
			<table>
				<tr>
					<td><h3>Amount due to customer:</h3></td>
					<td class="label1" id="show_total"><div class="sizing">0.00</div></td>
				</tr>
			</table>
		</div>		<div>
			<button class = "btn2" onclick="returns('<%= @cart_retruning.id %>')">Complete Return</button>
			<button class = "btn2" onclick="goto('<%= pos_path %>')">Return to POS</button>
		</div>
	</div>
</div>