config/routes.rb
Rails.application.routes.draw do
  resources :orders
  match '/recieving', to: 'orders#recieving', via: 'get', as: 'recieving'
  match '/remove_item', to: 'orders#remove_item', via: 'post', as: 'remove_item'
  match '/update_values', to: 'orders#update_values', via: 'post', as: 'update_values'
  match '/orders/print/:id', to: 'orders#print', via: 'get', as: 'print_order'

  resources :inventories

  resources :parts
  match '/catalog', to: 'parts#catalog', via: 'get', as: 'catalog'

  match '/add_part', to: 'carts#add_part', via: 'post', as: 'add_part'
  match '/remove_part', to: 'carts#remove_part', via: 'post', as: 'remove_part'
  match '/update_part', to: 'carts#update_part', via: 'post', as: 'update_part'
  match '/update_part_keep', to: 'carts#update_part_keep', via: 'post', as: 'update_part_keep'
  match '/item_count', to: 'carts#item_count', via: 'post', as: 'item_count'

  devise_for :users
  resources :users
  match '/users/add_user',    to: 'users#add_user',    via: 'post', as: 'add_user'
  match '/users/remove_user', to: 'users#remove_user', via: 'post', as: 'remove_user'
  match '/users/update_role', to: 'users#update_role', via: 'post', as: 'update_role'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

  match '/admin', to: 'admin#index', via: 'get', as: 'admin'

  match '/pos', to: 'pos#index', via: 'get', as: 'pos'
  match '/pos/returns', to: 'pos#returns', via: 'get', as: 'returns'
  match '/pos/recipt/:id', to: 'pos#recipt', via: 'get', as: 'recipt'

  resources :transactions, :only => [:show, :index, :destroy]
  match '/transactions/get_totals', to: 'transactions#get_totals', via: 'post', as: 'get_totals'
  match '/transactions/get_cart', to: 'transactions#get_cart', via: 'post', as: 'get_cart'
  match '/checkout', to: 'transactions#checkout', via: 'post', as: 'checkout'
  match '/return', to: 'transactions#return', via: 'post', as: 'return'

  match '/reports/daily', to: 'reports#daily', via: 'get', as: 'daily_report'
  match '/reports/weekly', to: 'reports#weekly', via: 'get', as: 'weekly_report'
  match '/reports/monthly', to: 'reports#monthly', via: 'get', as: 'monthly_report'
  match '/reports/quarterly', to: 'reports#quarterly', via: 'get', as: 'quarterly_report'
  match '/reports/yearly', to: 'reports#yearly', via: 'get', as: 'yearly_report'
  match '/reports/audit', to: 'reports#audit', via: 'get', as: 'audit_report'
  match '/reports/po', to: 'reports#po_report', via: 'get', as: 'po_report'
  match '/reports/inventory', to: 'reports#inventory', via: 'get', as: 'inventory_report'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  protect_from_forgery except: [:get_totals,:get_cart]
  before_filter :tier_one, only: [:index, :show, :get_totals, :get_cart]
  before_action :set_transaction, only: [:show, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  def show
    @cart = @transaction.cart
    @inCart = @cart.parts_in_cart
  end

  def destroy
    @transaction.return
    id = @transaction.id
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, flash: {success: "Transaction \##{id} was successfully destroyed." } }
      format.json { head :no_content }
    end
  end

  def get_totals
    cart = Cart.find(params[:cart_id])
    @subtotal = 0
    cart.parts_in_cart.each do |inCart|
      part = Part.find(inCart.part_id)
      @subtotal += (inCart.quantity_requested*part.price)
    end
    @tax = @subtotal*0.13
    @total = @subtotal+@tax
    @total = @total.round(2)
    respond_to do |format| # in this logic, going to respond with HTML or JSON  
        format.json{render :tally, status: 200}
    end
  end

  # The checkout api
  def checkout
    @transaction = Transaction.new
    @transaction.cart_id = current_user.cart.id
    @transaction.user = current_user
    @transaction.total = params[:transaction][:total].to_f
    @transaction.subtotal = params[:transaction][:subtotal].to_f
    @transaction.tax = params[:transaction][:tax].to_f
    @transaction.amount_given = params[:transaction][:amount_given].to_f
    @transaction.change = params[:transaction][:change].to_f
    @transaction.save!
    @transaction.checkout
    @cart = current_user.cart
    @cart.owner = params[:owners]
    current_user.cart = Cart.new
    current_user.cart.owner = current_user.username;
    current_user.save!
    respond_to do |format|
      if @transaction.save
        msg = {id: @transaction.id, message: "Success: Checkout \##{@transaction.id} was made" }
        flash[:success] = "Success: Checkout \##{@transaction.id} was made" 
        format.html { redirect_to :back, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, json: msg }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end


  ## basically get negative money totals, pulling up a cart
  def return
    @transaction = Transaction.new
    @transaction.cart_id = current_user.cart.id
    @transaction.user = current_user
    @transaction.total = params[:transaction][:total].to_f
    @transaction.subtotal = params[:transaction][:subtotal].to_f
    @transaction.tax = params[:transaction][:tax].to_f
    @transaction.amount_given = params[:transaction][:amount_given].to_f
    @transaction.change = params[:transaction][:change].to_f
    @transaction.save!
    @transaction.return
    @cart_retruning = Cart.find(session[:returns_cart])
    @cart_retruning.owner = ""
    @cart_retruning = Cart.new
    @cart_retruning.owner = "#{current_user.username}_returns"
    @cart_retruning.save!
    session[:returns_cart] = @cart_retruning.id 
    respond_to do |format|
      if @transaction.save
        flash[:success] = "Success: Return \##{@transaction.id} was made"
        format.html { redirect_to :back, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction, flash: flash }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_transaction_for_return
    @transaction = Transaction.find_by(params[:transaction_id])
    @cart_id = @transaction.cart_id
    @parts_in_cart = Cart.find_by(@cart_id).parts_in_cart
    respond_to do |format|
      format.json{render :get_cart, status: 200}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require[:transactions].permit[:transaction_id, :cart_id, :subtotal, :total, :tax, :amount_given, :change]
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Transactions</h1>

  <div class ="catalog_partial">
    <table class="table table-hover table-responsive table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Cashier</th>
          <th>Date</th>
          <th>Total</th>
          <th>Sub Total</th>
          <th>Taxes</th>
          <th>Tendered</th>
          <th>Change</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.id %></td>
            <td><%= transaction.cashier_username %></td>
            <td><%= l transaction.created_at, format: :common %></td>
            <td>$<%= transaction.total.round(2) %></td>
            <td>$<%= transaction.subtotal.round(2) %></td>
            <td>$<%= transaction.tax.round(2) %></td>
            <td>$<%= transaction.amount_given.round(2) %></td>
            <td>$<%= transaction.change.round(2) %></td>
            <td><%= link_to 'Show', transaction, class: "" %></td>
            <td><%= link_to 'Recipt', recipt_path(transaction.id, format: :pdf), class: ""  %></td>
            <td><%= link_to 'Destroy', transaction, class: "" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <button class = "btn2" onclick="goto('<%= pos_path  %>')">POS</button>
</div>

app/views/transactions/show.html.erb
<div class="container">

	<h1>Transaction <%= @transaction.id %></h1>

	<table class="table table-hover table-responsive">
		<thead>
			<tr>
				<th>Date</th>
				<th>Total</th>
				<th>Sub Total</th>
				<th>Taxes</th>
				<th>Tendered</th>
				<th>Change</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= l @transaction.created_at, format: :common %></td>
				<td>$<%= @transaction.total.round(2) %></td>
				<td>$<%= @transaction.subtotal.round(2) %></td>
				<td>$<%= @transaction.tax.round(2) %></td>
				<td>$<%= @transaction.amount_given.round(2) %></td>
				<td>$<%= @transaction.change.round(2) %></td>
			</tr>
		</tbody>
	</table>

	<h2>Items Transacted</h2>

	<div class ="parts_frame">
		<table class="table table-hover table-responsive table-striped">
			<thead>
				<tr>
					<th>Part #</th>
					<th>Price</th>
					<th>Quantity</th>
				</tr>
			</thead>
			<tbody>
				<% @inCart.each do |part| %>
					<tr>
						<td><%= Part.find(part.part_id).part_number %></td>
						<td><%= Part.find(part.part_id).price %></td>
						<td><%= part.quantity_requested %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>


	<%= link_to 'Back', transactions_path %>
</div>